### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by ChrisGeorgakidis** [cuhk-eda/ripple#1]
Trying to build the source code, the compiler causes the following error:

io/file_lefdef_db.cpp:313:25: error: variable 'direction' is uninitialized when
      used here [-Werror,-Wuninitialized]
                    if (direction == 'h') {
                        ^~~~~~~~~
io/file_lefdef_db.cpp:274:31: note: initialize the variable 'direction' to
      silence this warning
                char direction;
                              ^
                               = '\0'
1 error generated.
make: *** [io/file_lefdef_db.o] Error 1

**Comment by Rholais** [comment]
Thank you for raising the issue!
The function `readDEFPG` has been obsoleted so I cleaned up that part of code.

**Comment by ChrisGeorgakidis** [comment]
ok. thank you.
Now it generates the following error:
```
io/file_liberty.y:38.9-19: syntax error, unexpected identifier, expecting string
make: *** [io/file_liberty.tab.o] Error 1
```

**Comment by Rholais** [comment]
> ok. thank you.
> Now it generates the following error:
> 
> ```
> io/file_liberty.y:38.9-19: syntax error, unexpected identifier, expecting string
> make: *** [io/file_liberty.tab.o] Error 1
> ```

Thanks for the update.
May I know the version of `flex` in your environment?
Please try the latest version if possible.

**Comment by Rholais** [comment]
@ChrisGeorgakidis I will close the issue if there is no other problem regarding `flex`.

**Comment by Rholais** [comment]
@ChrisGeorgakidis I will close the issue if there is no other problem regarding `flex`.
