### ISSUE TITLE
Some starting guide for beginners

### ISSUE THREAD

**Issue by syue99** [cuhk-eda/ripple#10]
Hi. I am a physics grad student who is not really familiar with the VLSI context and I would like to use the ripple for placements of optimization problems on quantum annealers. Sorry for raising this post but I would like to know if there can be some simple example files that describes simple geometries (like place a K33 graph on a K6 graph) rather than the conference competition files (e.g. like superblue in ICCAD2012) so that I can test and build on from. Any information or reference is appreciated, thanks!

**Comment by Rholais** [comment]
Thanks for raising the issue.
May I know your data format?
`ripple` mainly works on Bookshelf and LEF/DEF formats.

**Comment by syue99** [comment]
Thanks for the reply! What I had now is a networkx graph for the annealer's topology (with a four dim coordinates (a,b,c,d) for every nodes and nodes with distance 1 are connected) and constraints of the variables we want to encode (connections). We want to use ripple to find the placement with minimal HPWL. The following can be an illustration of a  toy example:

Annealer nodes: (1,0,0,0), (2,0,0,0), (1,1,0,0), (1,2,0,0)
Edges: ((1,0,0,0), (2,0,0,0)), ((1,1,0,0), (1,2,0,0)), ((1,0,0,0),(1,1,0,0))

Var: 1,2,3
Connections: (1,3), (1,2)

**Comment by Rholais** [comment]
> Thanks for the reply! What I had now is a networkx graph for the annealer's topology (with a four dim coordinates (a,b,c,d) for every nodes and nodes with distance 1 are connected) and constraints of the variables we want to encode (connections). We want to use ripple to find the placement with minimal HPWL. The following can be an illustration of a toy example:
> 
> Annealer nodes: (1,0,0,0), (2,0,0,0), (1,1,0,0), (1,2,0,0) Edges: ((1,0,0,0), (2,0,0,0)), ((1,1,0,0), (1,2,0,0)), ((1,0,0,0),(1,1,0,0))
> 
> Var: 1,2,3 Connections: (1,3), (1,2)

Thanks for the explanation.
Ripple doesn't accept this kind of format for now.
Maybe you can consider translating it to LEF/DEF format and then use ripple for placement.

**Comment by Rholais** [comment]
@syue99 If there is no additional problem with the input format, I will close this issue.

**Comment by syue99** [comment]
Sure. I am trying to make it a Blif file and then LEF/DEF files. Thanks so much for the help!

**Comment by Rholais** [comment]
> Sure. I am trying to make it a Blif file and then LEF/DEF files. Thanks so much for the help!

Thanks for the confirmation.
I will close this issue and please feel free to open a new issue if there is more problem with the input format.
