### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by lh-power119** [cuhk-eda/ripple#5]
When I try to build the source code, I get the following error:
g++ -O3 -DNDEBUG   -Wall -std=c++17 -static  -I./lemon/include -I. -o placer main.o db/db.o db/db_cell.o db/db_layer.o db/db_net.o db/db_pin.o db/db_region.o db/db_drc.o db/db_geom.o db/db_route.o db/db_get.o db/db_set.o db/db_add.o db/db_map.o db/db_check.o db/db_place.o dp/dp.o dp/dp_data.o dp/dp_datalocal.o dp/dp_dataglobal.o dp/dp_draw.o dp/dp_move.o dp/dp_movemll.o dp/dp_movesr.o dp/dp_form.o dp/dp_place.o   io/file_bkshf_db.o io/file_constraints.o io/file_lefdef_db.o io/file_liberty.tab.o io/file_liberty.yy.o io/utils.o io/io.o io/file_verilog.o ripple/ripple.o  sta/lib.o sta/sta.o tcl/tcl.o ut/log.o ut/timer.o ut/utils.o vi/vi.o vi/draw.o vi/item_pos.o vi/vi_db.o def58/lib/libdef.a lef58/lib/liblef.a ./lemon/lib/libemon.a -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -ldl  
g++: error: def58/lib/libdef.a: does not have that file or directory
g++: error: lef58/lib/liblef.a: does not have that file or directory
g++: error: ./lemon/lib/libemon.a: does not have that file or directory
Makefile:152: recipe for target 'placer' failed
make: *** [placer] Error 1

**Comment by Rholais** [comment]
Thanks for reporting the error.
Can you help confirm your running directory and the command for compilation?

**Comment by lh-power119** [comment]
My run directory and compile command are as shown in the picture in the mail。










At 2022-02-26 00:21:34, "Rholais Lii" ***@***.***> wrote:

Thanks for reporting the error.
Can you help confirm your running directory and the command for compilation?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lh-power119** [comment]
My run directory and compile command looks like this:
lh@ubuntu:~$ cd Desktop/ripple-main/src
lh@ubuntu:~/Desktop/ripple-main/src$ make mode=release

**Comment by Rholais** [comment]
> My run directory and compile command looks like this:
> lh@ubuntu:$ cd Desktop/ripple-main/src
> lh@ubuntu:/Desktop/ripple-main/src$ make mode=release

Thanks for the prompt reply.
I force added the missing libraries.
Please pull and try again.

**Comment by Rholais** [comment]
@lh-power119  I will close the issue if there is no other problem regarding missing libraries.

**Comment by Rholais** [comment]
@lh-power119 I will close the issue if there is no other problem regarding missing libraries.
