### ISSUE TITLE
Sure.

### ISSUE THREAD

**Issue by darrenleeleelee1** [cuhk-eda/ripple#7]
Sure. 
The papers I mentioned are as follows:
https://www.researchgate.net/publication/221627056_Ripple_An_effective_routability-driven_placer_by_iterative_cell_movement
https://ieeexplore.ieee.org/document/6560745
https://dl.acm.org/doi/abs/10.1145/2925989
And the benchmarks I tried are as follows:
https://www.ispd.cc/contests/11/ispd2011_contest.html
http://archive.sigda.org/dac2012/contest/dac2012_contest_benchmarks.html#head-designs
BTW, when I used the superblue1 in ISPD11 with the following command 
./placer -bookshelf dac2012 -aux ../superblue1/superblue1.aux -pl ../superblue1/superblue1.pl -flow dac2016 -cpu 1,
it showed that bad::alloc.
Thanks for your help.

_Originally posted by @tstren1223 in https://github.com/cuhk-eda/ripple/issues/6#issuecomment-1121260252_

**Comment by Rholais** [comment]
Thanks for reporting the issue.
To use the source code for global placement, please try `-flow default` instead of `-flow dac2016`.

**Comment by Rholais** [comment]
The compilation command `make mode=release` is mainly for detailed placement tasks.
Can you try compiling with `make mode=release gr=`?
