### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by darrenleeleelee1** [cuhk-eda/ripple#8]
Hi there,
We also followed the your steps to build
but we get the error code.
![image](https://user-images.githubusercontent.com/56071442/168427557-8ffd1037-f540-48f5-ab38-2a6977f74cdf.png)
Which step did we do wrong?

and I also curious whether the line31 in db/db_geom.cpp is 

 ye = upperbound(ys.begin(), ys.end(), rect.hy)

![image](https://user-images.githubusercontent.com/56071442/168427677-c323ade3-64a0-45e4-a88f-d03d2326199d.png)

We complied the files followed by makefile
![image](https://user-images.githubusercontent.com/56071442/168456694-4e42a7c4-880c-4a46-b92f-17144bc8b2ca.png)
![image](https://user-images.githubusercontent.com/56071442/168456707-aa617434-e92c-4a38-ae87-456374d62d2d.png)

**Comment by Rholais** [comment]
Thanks for reporting the issue.
The compilation command `make mode=release` is mainly for detailed placement tasks.
Can you try compiling with `make mode=release gp=`?

**Comment by darrenleeleelee1** [comment]
Thanks for telling me that information.
But we compile with `make mode=release gr=` still stuck at the same spot.
![image](https://user-images.githubusercontent.com/56071442/168509253-f0f3d48e-3781-4d18-9f28-49274f84147f.png)

**Comment by Rholais** [comment]
> Thanks for telling me that information. But we compile with `make mode=release gr=` still stuck at the same spot. ![image](https://user-images.githubusercontent.com/56071442/168509253-f0f3d48e-3781-4d18-9f28-49274f84147f.png)

Apologize for the typo...
Can you try compiling with `make mode=release gp=`?

**Comment by darrenleeleelee1** [comment]
Thanks for telling me that typo.
I try `make mode=release gp=` and run with `./placer -bookshelf dac2012 -aux ../superblue4/superblue4.aux -pl ../superblue4/superblue4.pl -flow default -cpu 4`
But still got the segmentation fault.
Did you have any suggestion for me to fix this error?
![image](https://user-images.githubusercontent.com/56071442/168777325-2fad294c-b1ce-4bb2-9072-03eb081e5e44.png)

**Comment by darrenleeleelee1** [comment]
![image](https://user-images.githubusercontent.com/56071442/168786708-925474be-bd18-42ef-a183-1c30096ebc43.png)
Here is the value that I print out from ys which inside the db/db_geom.cpp.

**Comment by Rholais** [comment]
> Thanks for telling me that typo. I try `make mode=release gp=` and run with `./placer -bookshelf dac2012 -aux ../superblue4/superblue4.aux -pl ../superblue4/superblue4.pl -flow default -cpu 4` But still got the segmentation fault. Did you have any suggestion for me to fix this error? ![image](https://user-images.githubusercontent.com/56071442/168777325-2fad294c-b1ce-4bb2-9072-03eb081e5e44.png)

Are you working on the ICCAD2012 bookshelf format?
If so, can you try `-bookshelf iccad2012`?

**Comment by darrenleeleelee1** [comment]
It works thanks you.

**Comment by Rholais** [comment]
> It works thank you.

Thanks for the confirmation.
I will close the issue if there is no more question related to compilation.

**Comment by 0904-mansi** [comment]
> > It works thank you.
> 
> Thanks for the confirmation. I will close the issue if there is no more question related to compilation.

Hey, I am too facing a segmentation fault error while trying to import all files into my main python file. I am using Mac Monterey 12. Please help me
![Screenshot 2022-05-17 at 11 10 32 PM](https://user-images.githubusercontent.com/81081105/169292298-37a10611-d8a1-423e-a1f2-796134deb583.png)

**Comment by Rholais** [comment]
> > > It works thank you.
> > 
> > 
> > Thanks for the confirmation. I will close the issue if there is no more question related to compilation.
> 
> Hey, I am too facing a segmentation fault error while trying to import all files into my main python file. I am using Mac Monterey 12. Please help me![Screenshot 2022-05-17 at 11 10 32 PM](https://user-images.githubusercontent.com/81081105/169292298-37a10611-d8a1-423e-a1f2-796134deb583.png)

Thanks for raising the issue.
Are you able to run the binary from the command line instead of Python?

**Comment by darrenleeleelee1** [comment]
Sorry to bother you again, I run the command using `./placer -bookshelf iccad2012 -aux ../superblue4/superblue4.aux -pl ../superblue4/superblue4.pl -flow default -cpu 4` with the input superblue4 in https://www.ispd.cc/contests/11/ispd2011_contest.html
But I run the test with 33054.184 seconds, I think it is overtime.

**Comment by 0904-mansi** [comment]
> Sorry to bother you again, I run the command using `./placer -bookshelf iccad2012 -aux ../superblue4/superblue4.aux -pl ../superblue4/superblue4.pl -flow default -cpu 4` with the input superblue4 in https://www.ispd.cc/contests/11/ispd2011_contest.html But I run the test with 33054.184 seconds, I think it is overtime.

I was not able to solve this and I have to submit my project so I found another way to connect multiple files but this issue still exist..

**Comment by Rholais** [comment]
> Sorry to bother you again, but I run the command using `./placer -bookshelf iccad2012 -aux ../superblue4/superblue4.aux -pl ../superblue4/superblue4.pl -flow default -cpu 4` with the input superblue4 in https://www.ispd.cc/contests/11/ispd2011_contest.html But I run the test with 33054.184 seconds, I think it is overtime.

Thanks for the confirmation.
Can you attach the log files so that we can check the stage that takes most of the running time?

**Comment by Rholais** [comment]
> > Sorry to bother you again, but I run the command using `./placer -bookshelf iccad2012 -aux ../superblue4/superblue4.aux -pl ../superblue4/superblue4.pl -flow default -cpu 4` with the input superblue4 in https://www.ispd.cc/contests/11/ispd2011_contest.html But I run the test with 33054.184 seconds, I think it is overtime.
> 
> I could not solve this and had to submit my project so I found another way to connect multiple files but this issue still exists...

Congratulations on submitting your project!
Please feel free to open an issue and discuss the problem.

**Comment by darrenleeleelee1** [comment]
Thank you, I copy from the command line.
[   0.000]  -----------------------------------
[   0.000]    Ripple - placement tool
[   0.000]    Chinese University of Hong Kong
[   0.000]  -----------------------------------
[   0.000]  dir = ../superblue4/
[   2.953]  estimate site size = 1 x 9
[   2.953]  standard cell heights: 1 rows
reading net
reading route
reading shapes
reading weights
reading placement
reading scl
[  25.892]E Top power rail of the row at y=1800 is not connected to power rail
[  25.892]W Bottom power rail of the row at y=1800 is not connected to power rail
[  25.892]E Top and Bottom power rail of the row at y=1800 share the same power x
[  25.892]E Bottom power rail of the row at y=2700 is not connected to power rail
[  26.936]W track information missing for layer: M1
[  26.936]  Can't detect GcellGrid X Settings in DEF, set gcellTrackX=30 numGCellX=497 step=3000
[  26.936]  Can't detect GcellGrid Y Settings in DEF, set gcellTrackY=30 numGCellY=552 step=3000
[  27.554]  grids = 14899 x 16560 x 2
[  27.554]  mem = 470.595 MB
[  40.162]W missing net driving pin
[  40.162]W multiple net driving pin
[  41.258]  wirelength = 621664473.50 (scale=100.00)
[  44.105]  #nodes : 600220
[  44.105]  #nets  : 567607
[  44.105]  #pins  : 1884008
[  44.105]  #cells : 521466
[  44.105]  #macros: 78754
[  44.105]  #pads  : 0
[  44.168]  input wirelength = 621664473
[  44.261]  random wirelength = 7017856765
[ 152.009]  initial wirelength = 176786617
[ 469.310]  [ 1] up=318272471 lo=183918549
[ 829.357]  [ 2] up=290824736 lo=186149471
[1133.694]  [ 3] up=275633728 lo=188438028
[1428.833]  [ 4] up=263687547 lo=189066139
[1706.292]  [ 5] up=257251766 lo=190027177
[1983.506]  [ 6] up=253296937 lo=190982711
[2262.482]  [ 7] up=251226550 lo=191773411
[2539.049]  [ 8] up=245959829 lo=192660577
[2818.149]  [ 9] up=244725321 lo=193568081
[3084.275]  [10] up=242078722 lo=194470789
Restore ratio = -1
inflate too much, limit scale=0.773305
[3659.327]  [11] up=343225317 lo=200318984
Restore ratio = -1
inflate too much, limit scale=0.770334
[4262.105]  [12] up=329070407 lo=204858216
Restore ratio = -1
inflate too much, limit scale=0.769879
[4856.988]  [13] up=314709629 lo=208110815
Restore ratio = -1
inflate too much, limit scale=0.765612
[5458.106]  [14] up=309773241 lo=210351683
Restore ratio = -1
inflate too much, limit scale=0.768196
[6059.967]  [15] up=300363170 lo=212144315
Restore ratio = -1
inflate too much, limit scale=0.766518
[6656.496]  [16] up=296614351 lo=213922753
Restore ratio = -1
inflate too much, limit scale=0.767197
[7245.701]  [17] up=290625175 lo=215424505
Restore ratio = -1
inflate too much, limit scale=0.770128
[7820.487]  [18] up=286603612 lo=216703606
Restore ratio = -1
inflate too much, limit scale=0.766561
[8393.779]  [19] up=285931279 lo=217655395
Restore ratio = -1
inflate too much, limit scale=0.764269
[8974.802]  [20] up=282022507 lo=218840193
Restore ratio = -1
inflate too much, limit scale=0.764229
[9539.977]  [21] up=282019876 lo=219812486
Restore ratio = -1
inflate too much, limit scale=0.770114
[10111.931]  [22] up=277220546 lo=220709621
Restore ratio = -1
inflate too much, limit scale=0.767223
[10667.336]  [23] up=280168765 lo=221359586
Restore ratio = -1
inflate too much, limit scale=0.766277
[11223.027]  [24] up=275395692 lo=222194483
Restore ratio = -1
inflate too much, limit scale=0.766938
[11775.417]  [25] up=273919801 lo=223078790
Restore ratio = -1
inflate too much, limit scale=0.765755
[12314.569]  [26] up=271537174 lo=223739533
Restore ratio = -1
inflate too much, limit scale=0.76722
[12854.801]  [27] up=268588247 lo=224477803
Restore ratio = -1
inflate too much, limit scale=0.766314
[13389.969]  [28] up=269016404 lo=225146438
Restore ratio = -1
inflate too much, limit scale=0.766949
[13924.022]  [29] up=269334761 lo=225787191
Restore ratio = -1
inflate too much, limit scale=0.767464
[14518.984]  [30] up=267972128 lo=226334583
Restore ratio = -1
inflate too much, limit scale=0.764794
[15086.709]  [31] up=265283292 lo=226831116
Restore ratio = -1
inflate too much, limit scale=0.766407
[15639.501]  [32] up=266531552 lo=227347781
Restore ratio = -1
inflate too much, limit scale=0.766224
[16189.321]  [33] up=264948608 lo=227756164
Restore ratio = -1
inflate too much, limit scale=0.767805
[16728.505]  [34] up=264554974 lo=228133956
Restore ratio = -1
inflate too much, limit scale=0.766812
[17273.358]  [35] up=263513419 lo=228589678
Restore ratio = -1
inflate too much, limit scale=0.769314
[17810.032]  [36] up=264582752 lo=228993745
Restore ratio = -1
inflate too much, limit scale=0.766958
[18329.653]  [37] up=262869673 lo=229322950
Restore ratio = -1
inflate too much, limit scale=0.76589
[18843.106]  [38] up=262262206 lo=229624992
Restore ratio = -1
inflate too much, limit scale=0.766897
[19347.105]  [39] up=261953895 lo=230002462
Restore ratio = -1
inflate too much, limit scale=0.767451
[19851.871]  [40] up=262364987 lo=230389813
Restore ratio = -1
inflate too much, limit scale=0.76934
[20360.434]  [41] up=261540579 lo=230716417
Restore ratio = -1
inflate too much, limit scale=0.767014
[20864.661]  [42] up=262842832 lo=231005081
Restore ratio = -1
inflate too much, limit scale=0.76615
[21367.511]  [43] up=261057502 lo=231284033
Restore ratio = -1
inflate too much, limit scale=0.767873
[21871.043]  [44] up=260094381 lo=231503934
Restore ratio = -1
inflate too much, limit scale=0.76689
[22380.752]  [45] up=262071615 lo=231785597
Restore ratio = -1
inflate too much, limit scale=0.763404
[22882.880]  [46] up=259298100 lo=231996839
Restore ratio = -1
inflate too much, limit scale=0.765648
[23389.135]  [47] up=259439789 lo=232196590
Restore ratio = -1
inflate too much, limit scale=0.76705
[23885.830]  [48] up=258728642 lo=232426099
Restore ratio = -1
inflate too much, limit scale=0.766284
[24377.308]  [49] up=258486884 lo=232685635
Restore ratio = -1
inflate too much, limit scale=0.767502
[24864.103]  [50] up=258808090 lo=232872211
[25128.790]E Unable to open DEF:
[25128.791]  ./iccad19gr -lef  -def ripple_2022_05_18_11_58_30/gp_18_57_19_cugr/placed.def -output ripple_2022_05_18_11_58_30/gp_18_57_19_cugr/tmp.guide -threads 8 -rrrIters 1 -cgmap ripple_2022_05_18_11_58_30/gp_18_57_19_cugr/cugr_congestion.txt

sh: 1: ./iccad19gr: not found
[25128.850]  The value returned was: 32512.

[25128.850]  Loading CUGR's output file!
[25128.850]E Unable to open TXT: ripple_2022_05_18_11_58_30/gp_18_57_19_cugr/cugr_congestion.txt
Restore ratio = -1
inflate too much, limit scale=0.768134
[25207.548]  [51] up=258126565 lo=233125391
[25466.930]E Unable to open DEF:
[25466.930]  ./iccad19gr -lef  -def ripple_2022_05_18_11_58_30/gp_19_02_57_cugr/placed.def -output ripple_2022_05_18_11_58_30/gp_19_02_57_cugr/tmp.guide -threads 8 -rrrIters 1 -cgmap ripple_2022_05_18_11_58_30/gp_19_02_57_cugr/cugr_congestion.txt

sh: 1: ./iccad19gr: not found
[25466.980]  The value returned was: 32512.

[25466.980]  Loading CUGR's output file!
[25466.980]E Unable to open TXT: ripple_2022_05_18_11_58_30/gp_19_02_57_cugr/cugr_congestion.txt
Restore ratio = -1
inflate too much, limit scale=0.769433
[25539.935]  [52] up=257944744 lo=233130289
[25803.629]E Unable to open DEF:
[25803.629]  ./iccad19gr -lef  -def ripple_2022_05_18_11_58_30/gp_19_08_33_cugr/placed.def -output ripple_2022_05_18_11_58_30/gp_19_08_33_cugr/tmp.guide -threads 8 -rrrIters 1 -cgmap ripple_2022_05_18_11_58_30/gp_19_08_33_cugr/cugr_congestion.txt

sh: 1: ./iccad19gr: not found
[25803.639]  The value returned was: 32512.

[25803.639]  Loading CUGR's output file!
[25803.639]E Unable to open TXT: ripple_2022_05_18_11_58_30/gp_19_08_33_cugr/cugr_congestion.txt
Restore ratio = -1
inflate too much, limit scale=0.76839
[25878.797]  [53] up=258246303 lo=233415296
[26141.437]E Unable to open DEF:
[26141.438]  ./iccad19gr -lef  -def ripple_2022_05_18_11_58_30/gp_19_14_11_cugr/placed.def -output ripple_2022_05_18_11_58_30/gp_19_14_11_cugr/tmp.guide -threads 8 -rrrIters 1 -cgmap ripple_2022_05_18_11_58_30/gp_19_14_11_cugr/cugr_congestion.txt

sh: 1: ./iccad19gr: not found
[26141.439]  The value returned was: 32512.

[26141.439]  Loading CUGR's output file!
[26141.439]E Unable to open TXT: ripple_2022_05_18_11_58_30/gp_19_14_11_cugr/cugr_congestion.txt
Restore ratio = -1
inflate too much, limit scale=0.769763
[26217.752]  [54] up=257953815 lo=233608129
[26320.086]  final=243031734
[26320.146]  output wirelength = 243031734
[26320.146]  global place runtime = 26276.04
[26321.323]  wirelength = 243031723.38 (scale=100.00)
[26376.561]E number of dp types is 12262
[33033.083]  [  ][0] dbDisp = 346504 dbMean = 0.073 dbMean1 = 0.073 dbMean2 = -0.001 dbMean3 = -0.001 dbMean4 = -0.001 dbMax = 0.6 HPWL = 243036522 (iter=0.00%) (total=0.00%) overlap = 0 unplaced = 521466 overlapSum = 0
[33033.657]  [PM][0] dbDisp = 691818 dbMean = 0.146 dbMean1 = 0.146 dbMean2 = -0.001 dbMean3 = -0.001 dbMean4 = -0.001 dbMax = 95.9 HPWL = 243109961 (iter=0.03%) (total=0.03%) overlap = 0 unplaced = 521466 overlapSum = 0
[33049.829]  [LG][0] dbDisp = 1516002 dbMean = 0.322 dbMean1 = 0.322 dbMean2 = -0.001 dbMean3 = -0.001 dbMean4 = -0.001 dbMax = 263.6 HPWL = 243718666 (iter=0.25%) (total=0.28%) overlap = 0 unplaced = 0 overlapSum = 0
[33051.584]  cell: o312518      fid: 0  type: o312518   nCells: 2000    Total flow cost: 185544.272640  Max Disp: 2372.250000->2242.250000
[33052.099]  [CM][0] dbDisp = 1517684 dbMean = 0.322 dbMean1 = 0.322 dbMean2 = -0.001 dbMean3 = -0.001 dbMean4 = -0.001 dbMax = 261.5 HPWL = 243721603 (iter=0.00%) (total=0.28%) overlap = 0 unplaced = 0 overlapSum = 0
[33053.347]  cell: o312517      fid: 0  type: o312517   nCells: 2002    Total flow cost: 272822.950336  Max Disp: 2353.500000->2052.000000
[33053.842]  [CM][1] dbDisp = 1519825 dbMean = 0.323 dbMean1 = 0.323 dbMean2 = -0.001 dbMean3 = -0.001 dbMean4 = -0.001 dbMax = 259.5 HPWL = 243724479 (iter=0.00%) (total=0.28%) overlap = 0 unplaced = 0 overlapSum = 0
[33054.184]  cell: o312387      fid: 0  type: o312387   nCells: 1531    Total flow cost: 198045.537588

**Comment by Rholais** [comment]
> Thank you, I copy from the command line. [ 0.000] ----------------------------------- [ 0.000] Ripple - placement tool [ 0.000] Chinese University of Hong Kong [ 0.000] ----------------------------------- [ 0.000] dir = ../superblue4/ [ 2.953] estimate site size = 1 x 9 [ 2.953] standard cell heights: 1 rows reading net reading route reading shapes reading weights reading placement reading scl [ 25.892]E Top power rail of the row at y=1800 is not connected to power rail [ 25.892]W Bottom power rail of the row at y=1800 is not connected to power rail [ 25.892]E Top and Bottom power rail of the row at y=1800 share the same power x [ 25.892]E Bottom power rail of the row at y=2700 is not connected to power rail [ 26.936]W track information missing for layer: M1 [ 26.936] Can't detect GcellGrid X Settings in DEF, set gcellTrackX=30 numGCellX=497 step=3000 [ 26.936] Can't detect GcellGrid Y Settings in DEF, set gcellTrackY=30 numGCellY=552 step=3000 [ 27.554] grids = 14899 x 16560 x 2 [ 27.554] mem = 470.595 MB [ 40.162]W missing net driving pin [ 40.162]W multiple net driving pin [ 41.258] wirelength = 621664473.50 (scale=100.00) [ 44.105] #nodes : 600220 [ 44.105] #nets : 567607 [ 44.105] #pins : 1884008 [ 44.105] #cells : 521466 [ 44.105] #macros: 78754 [ 44.105] #pads : 0 [ 44.168] input wirelength = 621664473 [ 44.261] random wirelength = 7017856765 [ 152.009] initial wirelength = 176786617 [ 469.310] [ 1] up=318272471 lo=183918549 [ 829.357] [ 2] up=290824736 lo=186149471 [1133.694] [ 3] up=275633728 lo=188438028 [1428.833] [ 4] up=263687547 lo=189066139 [1706.292] [ 5] up=257251766 lo=190027177 [1983.506] [ 6] up=253296937 lo=190982711 [2262.482] [ 7] up=251226550 lo=191773411 [2539.049] [ 8] up=245959829 lo=192660577 [2818.149] [ 9] up=244725321 lo=193568081 [3084.275] [10] up=242078722 lo=194470789 Restore ratio = -1 inflate too much, limit scale=0.773305 [3659.327] [11] up=343225317 lo=200318984 Restore ratio = -1 inflate too much, limit scale=0.770334 [4262.105] [12] up=329070407 lo=204858216 Restore ratio = -1 inflate too much, limit scale=0.769879 [4856.988] [13] up=314709629 lo=208110815 Restore ratio = -1 inflate too much, limit scale=0.765612 [5458.106] [14] up=309773241 lo=210351683 Restore ratio = -1 inflate too much, limit scale=0.768196 [6059.967] [15] up=300363170 lo=212144315 Restore ratio = -1 inflate too much, limit scale=0.766518 [6656.496] [16] up=296614351 lo=213922753 Restore ratio = -1 inflate too much, limit scale=0.767197 [7245.701] [17] up=290625175 lo=215424505 Restore ratio = -1 inflate too much, limit scale=0.770128 [7820.487] [18] up=286603612 lo=216703606 Restore ratio = -1 inflate too much, limit scale=0.766561 [8393.779] [19] up=285931279 lo=217655395 Restore ratio = -1 inflate too much, limit scale=0.764269 [8974.802] [20] up=282022507 lo=218840193 Restore ratio = -1 inflate too much, limit scale=0.764229 [9539.977] [21] up=282019876 lo=219812486 Restore ratio = -1 inflate too much, limit scale=0.770114 [10111.931] [22] up=277220546 lo=220709621 Restore ratio = -1 inflate too much, limit scale=0.767223 [10667.336] [23] up=280168765 lo=221359586 Restore ratio = -1 inflate too much, limit scale=0.766277 [11223.027] [24] up=275395692 lo=222194483 Restore ratio = -1 inflate too much, limit scale=0.766938 [11775.417] [25] up=273919801 lo=223078790 Restore ratio = -1 inflate too much, limit scale=0.765755 [12314.569] [26] up=271537174 lo=223739533 Restore ratio = -1 inflate too much, limit scale=0.76722 [12854.801] [27] up=268588247 lo=224477803 Restore ratio = -1 inflate too much, limit scale=0.766314 [13389.969] [28] up=269016404 lo=225146438 Restore ratio = -1 inflate too much, limit scale=0.766949 [13924.022] [29] up=269334761 lo=225787191 Restore ratio = -1 inflate too much, limit scale=0.767464 [14518.984] [30] up=267972128 lo=226334583 Restore ratio = -1 inflate too much, limit scale=0.764794 [15086.709] [31] up=265283292 lo=226831116 Restore ratio = -1 inflate too much, limit scale=0.766407 [15639.501] [32] up=266531552 lo=227347781 Restore ratio = -1 inflate too much, limit scale=0.766224 [16189.321] [33] up=264948608 lo=227756164 Restore ratio = -1 inflate too much, limit scale=0.767805 [16728.505] [34] up=264554974 lo=228133956 Restore ratio = -1 inflate too much, limit scale=0.766812 [17273.358] [35] up=263513419 lo=228589678 Restore ratio = -1 inflate too much, limit scale=0.769314 [17810.032] [36] up=264582752 lo=228993745 Restore ratio = -1 inflate too much, limit scale=0.766958 [18329.653] [37] up=262869673 lo=229322950 Restore ratio = -1 inflate too much, limit scale=0.76589 [18843.106] [38] up=262262206 lo=229624992 Restore ratio = -1 inflate too much, limit scale=0.766897 [19347.105] [39] up=261953895 lo=230002462 Restore ratio = -1 inflate too much, limit scale=0.767451 [19851.871] [40] up=262364987 lo=230389813 Restore ratio = -1 inflate too much, limit scale=0.76934 [20360.434] [41] up=261540579 lo=230716417 Restore ratio = -1 inflate too much, limit scale=0.767014 [20864.661] [42] up=262842832 lo=231005081 Restore ratio = -1 inflate too much, limit scale=0.76615 [21367.511] [43] up=261057502 lo=231284033 Restore ratio = -1 inflate too much, limit scale=0.767873 [21871.043] [44] up=260094381 lo=231503934 Restore ratio = -1 inflate too much, limit scale=0.76689 [22380.752] [45] up=262071615 lo=231785597 Restore ratio = -1 inflate too much, limit scale=0.763404 [22882.880] [46] up=259298100 lo=231996839 Restore ratio = -1 inflate too much, limit scale=0.765648 [23389.135] [47] up=259439789 lo=232196590 Restore ratio = -1 inflate too much, limit scale=0.76705 [23885.830] [48] up=258728642 lo=232426099 Restore ratio = -1 inflate too much, limit scale=0.766284 [24377.308] [49] up=258486884 lo=232685635 Restore ratio = -1 inflate too much, limit scale=0.767502 [24864.103] [50] up=258808090 lo=232872211 [25128.790]E Unable to open DEF: [25128.791] ./iccad19gr -lef -def ripple_2022_05_18_11_58_30/gp_18_57_19_cugr/placed.def -output ripple_2022_05_18_11_58_30/gp_18_57_19_cugr/tmp.guide -threads 8 -rrrIters 1 -cgmap ripple_2022_05_18_11_58_30/gp_18_57_19_cugr/cugr_congestion.txt
> 
> sh: 1: ./iccad19gr: not found [25128.850] The value returned was: 32512.
> 
> [25128.850] Loading CUGR's output file! [25128.850]E Unable to open TXT: ripple_2022_05_18_11_58_30/gp_18_57_19_cugr/cugr_congestion.txt Restore ratio = -1 inflate too much, limit scale=0.768134 [25207.548] [51] up=258126565 lo=233125391 [25466.930]E Unable to open DEF: [25466.930] ./iccad19gr -lef -def ripple_2022_05_18_11_58_30/gp_19_02_57_cugr/placed.def -output ripple_2022_05_18_11_58_30/gp_19_02_57_cugr/tmp.guide -threads 8 -rrrIters 1 -cgmap ripple_2022_05_18_11_58_30/gp_19_02_57_cugr/cugr_congestion.txt
> 
> sh: 1: ./iccad19gr: not found [25466.980] The value returned was: 32512.
> 
> [25466.980] Loading CUGR's output file! [25466.980]E Unable to open TXT: ripple_2022_05_18_11_58_30/gp_19_02_57_cugr/cugr_congestion.txt Restore ratio = -1 inflate too much, limit scale=0.769433 [25539.935] [52] up=257944744 lo=233130289 [25803.629]E Unable to open DEF: [25803.629] ./iccad19gr -lef -def ripple_2022_05_18_11_58_30/gp_19_08_33_cugr/placed.def -output ripple_2022_05_18_11_58_30/gp_19_08_33_cugr/tmp.guide -threads 8 -rrrIters 1 -cgmap ripple_2022_05_18_11_58_30/gp_19_08_33_cugr/cugr_congestion.txt
> 
> sh: 1: ./iccad19gr: not found [25803.639] The value returned was: 32512.
> 
> [25803.639] Loading CUGR's output file! [25803.639]E Unable to open TXT: ripple_2022_05_18_11_58_30/gp_19_08_33_cugr/cugr_congestion.txt Restore ratio = -1 inflate too much, limit scale=0.76839 [25878.797] [53] up=258246303 lo=233415296 [26141.437]E Unable to open DEF: [26141.438] ./iccad19gr -lef -def ripple_2022_05_18_11_58_30/gp_19_14_11_cugr/placed.def -output ripple_2022_05_18_11_58_30/gp_19_14_11_cugr/tmp.guide -threads 8 -rrrIters 1 -cgmap ripple_2022_05_18_11_58_30/gp_19_14_11_cugr/cugr_congestion.txt
> 
> sh: 1: ./iccad19gr: not found [26141.439] The value returned was: 32512.
> 
> [26141.439] Loading CUGR's output file!
> [26141.439]E Unable to open TXT: ripple_2022_05_18_11_58_30/gp_19_14_11_cugr/cugr_congestion.txt Restore ratio = -1 inflate too much, limit scale=0.769763 [26217.752] [54] up=257953815 lo=233608129 [26320.086] final=243031734 [26320.146] output wirelength = 243031734 [26320.146] global place runtime = 26276.04 [26321.323] wirelength = 243031723.38 (scale=100.00) [26376.561]E number of dp types is 12262 [33033.083] [ ][0] dbDisp = 346504 dbMean = 0.073 dbMean1 = 0.073 dbMean2 = -0.001 dbMean3 = -0.001 dbMean4 = -0.001 dbMax = 0.6 HPWL = 243036522 (iter=0.00%) (total=0.00%) overlap = 0 unplaced = 521466 overlapSum = 0 [33033.657] [PM][0] dbDisp = 691818 dbMean = 0.146 dbMean1 = 0.146 dbMean2 = -0.001 dbMean3 = -0.001 dbMean4 = -0.001 dbMax = 95.9 HPWL = 243109961 (iter=0.03%) (total=0.03%) overlap = 0 unplaced = 521466 overlapSum = 0 [33049.829] [LG][0] dbDisp = 1516002 dbMean = 0.322 dbMean1 = 0.322 dbMean2 = -0.001 dbMean3 = -0.001 dbMean4 = -0.001 dbMax = 263.6 HPWL = 243718666 (iter=0.25%) (total=0.28%) overlap = 0 unplaced = 0 overlapSum = 0 [33051.584] cell: o312518 fid: 0 type: o312518 nCells: 2000 Total flow cost: 185544.272640 Max Disp: 2372.250000->2242.250000 [33052.099] [CM][0] dbDisp = 1517684 dbMean = 0.322 dbMean1 = 0.322 dbMean2 = -0.001 dbMean3 = -0.001 dbMean4 = -0.001 dbMax = 261.5 HPWL = 243721603 (iter=0.00%) (total=0.28%) overlap = 0 unplaced = 0 overlapSum = 0 [33053.347] cell: o312517 fid: 0 type: o312517 nCells: 2002 Total flow cost: 272822.950336 Max Disp: 2353.500000->2052.000000 [33053.842] [CM][1] dbDisp = 1519825 dbMean = 0.323 dbMean1 = 0.323 dbMean2 = -0.001 dbMean3 = -0.001 dbMean4 = -0.001 dbMax = 259.5 HPWL = 243724479 (iter=0.00%) (total=0.28%) overlap = 0 unplaced = 0 overlapSum = 0 [33054.184] cell: o312387 fid: 0 type: o312387 nCells: 1531 Total flow cost: 198045.537588

Thanks for sharing the log.
It seems that the global routing binary is not found and you can try `-gp_num_gr_iter 0` to disable global-routing-based congestion repairment.

**Comment by darrenleeleelee1** [comment]
Sorry for replying so late, thanks for helping.

**Comment by Rholais** [comment]
> Sorry for replying so late, thanks for helping.

No problem.
If there is no additional problem with the running time, I will close this issue.

**Comment by Rholais** [comment]
@darrenleeleelee1 If there is no additional problem with the running time, I will close this issue.
