### ISSUE TITLE
-bookshelf wu2016

### ISSUE THREAD

**Issue by darrenleeleelee1** [cuhk-eda/ripple#9]
Hi there, I am curious about what is the flag `-bookshelf wu2016` stand for?
Or what flag can I use ripple without routing?
Thanks.

**Comment by Rholais** [comment]
Thanks for raising the issue.
`-bookshelf wu2016` is to work with a benchmark from another paper.
To disable global-routing-based congestion repairment, please try `-gp_num_gr_iter 0` as I mentioned in #8

**Comment by darrenleeleelee1** [comment]
Thanks, I will try it.
